### ISSUE TITLE
Creación de landing page

### ISSUE THREAD

**Issue by Sii-Cuidamos** [siicuidamos/sii-cuidamos#18]

**Comment by gabrielpintop** [comment]
La implementación realizada mejor de forma significativa la página inicial de la aplicación, sin embargo, encontré los siguientes aspectos por mejorar:

- [ ] Opino que podríamos centrar la información junto con el logo en la vista de PC con el fin de buscar una mejor armonía en el navbar
- [ ] Sugiero revisar las dimensiones de las imágenes usadas tanto en el navbar, como en el landing container y el footer. Buscando que tengan un tamaño acorde al tamaño de la pantalla desde la cual se accede a la aplicación
- [ ] Siento que podríamos usar alguno de los patrones de diseño más usados actualmente para el conjunto navbar-footer, ya sea el navbar del ancho completo al igual que el footer, o el navbar completo y el footer del ancho de un container con margenes a los lados de ancho de la misma longitud 
- [ ] Me gustaría que habláramos con el equipo sobre la paleta de colores a utilizar al igual que la opacidad de los textos en toda la aplicación en general, pero empezando con el landing
- [ ] Teniendo en cuenta que agregaste los logos de redes sociales (Facebook, Twitter e Instagram), me surge la duda de si, ¿Deberíamos crearlos? Y de ser así, ¿Qué sea lo más pronto posible para habilitar los enlaces?
